version: '3'
services:
  node-app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    image: node:14

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
